name: camera-seg
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - pillow
  - yaml
  - pyyaml
  - matplotlib
  - jupyter
  - notebook
  - tensorboardx
  - tensorboard
  - protobuf
  - tqdm
  - pip:
    - torch
    - torchvision
    - -r requirements.txt